
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- hl.config({ autogenerated = true }) -- remove this line to remove the warning

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
--hl.monitor({
    -- output   = "",
   -- mode     = "preferred",
  --  position = "auto",
 --   scale    = "auto",
--})


hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "0x0",    scale = "auto" })
hl.monitor({ output = "DP-1",     mode = "preferred", position = "1280x0", scale = "auto" })


---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = "hyprlauncher"


-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function () 
	-- restore the remembered shell, then lock immediately (stands in for a
	-- display manager); the lock follows the shell: caelestia's lock under
	-- caelestia, else hyprlock. First, so the lock comes up before the apps.
	hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/shell-restore.sh --lock")
	hl.exec_cmd(terminal)
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("firefox")
	-- wallpaper daemon + re-apply the last used wallpaper
	hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper-restore.sh")
	hl.exec_cmd("hyprpolkitagent")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPRSHOT_DIR", "~/Pictures/Screenshots")

-- Route Qt apps (dolphin, and any other Qt6 app) through qt6ct, which is
-- what reads the wallpaper-derived colour scheme in ~/.config/qt6ct/.
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")


-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/

-- Wallpaper-derived colours, written by ~/.config/theme/theme-apply.sh.
-- dofile with an absolute path rather than require(), because Hyprland's Lua
-- package.path does not necessarily include ~/.config/hypr. Wrapped in pcall
-- so that a missing or malformed colors.lua degrades to these defaults
-- instead of breaking the entire config.
local colors = (function()
    local ok, generated = pcall(dofile, os.getenv("HOME") .. "/.config/hypr/colors.lua")
    if ok and type(generated) == "table" and generated.active_border then
        return generated
    end
    return {
        active_border   = { colors = {"rgba(33ccffee)", "rgba(00ff99ee)"}, angle = 45 },
        inactive_border = "rgba(595959aa)",
        shadow_color    = 0xee1a1a1a,
    }
end)()

local gapsOut = 20

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = gapsOut,

        border_size = 2,

        col = {
            active_border   = colors.active_border,
            inactive_border = colors.inactive_border,
        },

        -- Set to true to enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,

        -- Please see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/ before you turn this on
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        -- Change transparency of focused and unfocused windows
        active_opacity   = 1,
        inactive_opacity = 1,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = colors.shadow_color,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })

-- Default springs
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global",        enabled = true,  speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true,  speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true,  speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true,  speed = 4.1,  spring = "easy",         style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true,  speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true,  speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true,  speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true,  speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true,  speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true,  speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true,  speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true,  speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true,  speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true,  speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true,  speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true,  speed = 7,    bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- Bind workspaces to monitors.
-- 1-5 live on the ultrawide, 6-10 on the portable panel. Pressing a workspace
-- key that belongs to the other monitor moves focus there automatically.
local workspaceMonitors = {
    { output = "DP-1",     workspaces = { 1, 2, 3, 4, 5 },   default = 1 },
    { output = "HDMI-A-1", workspaces = { 6, 7, 8, 9, 10 },  default = 6 },
}

for _, m in ipairs(workspaceMonitors) do
    for _, ws in ipairs(m.workspaces) do
        hl.workspace_rule({
            workspace  = tostring(ws),
            monitor    = m.output,
            persistent = true,
            default    = (ws == m.default),
        })
    end
end

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
    master = {
        new_status = "master",
    },
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
    scrolling = {
        fullscreen_on_one_column = true,
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
local closeWindowBind = hl.bind(mainMod .. " + C", hl.dsp.window.close())
-- closeWindowBind:set_enabled(false)
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit"))
-- hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("hyprlock"))  -- moved to caelestia-gated bind below
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
-- hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))  -- moved to caelestia-gated bind below
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("librewolf"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/wallpaper-picker.sh"))
-- Flip the current theme between its light and dark variant, same wallpaper.
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/theme/theme-toggle.sh"))
-- W = wallpaper, SHIFT + W = theme, CTRL + W = shell: the whole "look" family on one key.
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/shell-picker.sh"))

hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit"))    -- dwindle only

-- Other Utils
-- hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("hyprshot -m region"))  -- moved to caelestia-gated bind below

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Move the focused tile into the neighbouring slot (re-inserts it in the layout tree).
-- movewindow parks a floating window flush against the screen edge; nudge it back in
-- by gaps_out so floaters line up with the tiles. Tiled windows are untouched.
local function moveWindow(direction)
    return function()
        hl.dispatch(hl.dsp.window.move({ direction = direction }))
        local win = hl.get_active_window()
        if not (win and win.floating) then
            return
        end
        local dx = direction == "left" and gapsOut or direction == "right" and -gapsOut or 0
        local dy = direction == "up" and gapsOut or direction == "down" and -gapsOut or 0
        hl.dispatch(hl.dsp.window.move({ x = dx, y = dy, relative = true }))
    end
end
hl.bind(mainMod .. " + SHIFT + left",  moveWindow("left"),  { description = "Move window left" })
hl.bind(mainMod .. " + SHIFT + right", moveWindow("right"), { description = "Move window right" })
hl.bind(mainMod .. " + SHIFT + up",    moveWindow("up"),    { description = "Move window up" })
hl.bind(mainMod .. " + SHIFT + down",  moveWindow("down"),  { description = "Move window down" })

-- Swap places with the neighbour, layout tree unchanged
hl.bind(mainMod .. " + ALT + left",  hl.dsp.window.swap({ direction = "left" }),  { description = "Swap window left" })
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.swap({ direction = "right" }), { description = "Swap window right" })
hl.bind(mainMod .. " + ALT + up",    hl.dsp.window.swap({ direction = "up" }),    { description = "Swap window up" })
hl.bind(mainMod .. " + ALT + down",  hl.dsp.window.swap({ direction = "down" }),  { description = "Swap window down" })

-- Resize the focused window (tiled or floating); repeats while held
hl.bind(mainMod .. " + CTRL + left",  hl.dsp.window.resize({ x = -40, y = 0,   relative = true }), { repeating = true, description = "Shrink window horizontally" })
hl.bind(mainMod .. " + CTRL + right", hl.dsp.window.resize({ x = 40,  y = 0,   relative = true }), { repeating = true, description = "Grow window horizontally" })
hl.bind(mainMod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -40, relative = true }), { repeating = true, description = "Shrink window vertically" })
hl.bind(mainMod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 40,  relative = true }), { repeating = true, description = "Grow window vertically" })

-- Fullscreen (covers the bar) / maximised (keeps bar and gaps); both toggle
hl.bind(mainMod .. " + F",         hl.dsp.window.fullscreen({ mode = "fullscreen" }), { description = "Toggle fullscreen" })
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "maximized" }),  { description = "Toggle maximised" })

-- Float toggle that also works under caelestia (SUPER + V is the clipboard there), and centre a floater
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.bind(mainMod .. " + ALT + C",   hl.dsp.window.center(),                     { description = "Centre floating window" })

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
-- hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
-- hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
-- hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })  -- moved to caelestia-gated bind below
-- hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })  -- moved to caelestia-gated bind below

-- Requires playerctl
-- hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })  -- moved to caelestia-gated bind below
-- hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })  -- moved to caelestia-gated bind below
-- hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })  -- moved to caelestia-gated bind below
-- hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })  -- moved to caelestia-gated bind below

-- Caelestia shell (only active while the caelestia quickshell config is running; see scripts/shell-bind.sh)
-- Keys shared with a bind above go through shell-bind.sh, which runs the
-- caelestia action under caelestia and the original command under any other
-- config; the originals are commented out above so the key doesn't fire twice.
-- Plain global shortcuts need no gate: nobody owns them without caelestia.
local shellBind = os.getenv("HOME") .. "/.config/hypr/scripts/shell-bind.sh"
-- %q double-quotes each command; its \" and \\ escapes are ones sh undoes too,
-- but $ and ` are left alone, so commands must not rely on those.
local function gated(caelestiaCmd, fallbackCmd)
    return hl.dsp.exec_cmd(string.format("%s %q %q", shellBind, caelestiaCmd, fallbackCmd or ""))
end
-- Shell command that fires a caelestia global shortcut. Under a Lua config
-- `hyprctl dispatch` takes a Lua dispatcher expression, not `global <name>`.
local function globalCmd(name)
    return string.format([[hyprctl dispatch "hl.dsp.global('caelestia:%s')"]], name)
end

-- Shared keys: caelestia action, else the original bind's command
hl.bind(mainMod .. " + L",         gated(globalCmd("lock"), "hyprlock"))
hl.bind(mainMod .. " + V",         gated("caelestia clipboard", "hyprctl dispatch \"hl.dsp.window.float({ action = 'toggle' })\""))
hl.bind(mainMod .. " + SHIFT + S", gated(globalCmd("screenshotFreeze"), "hyprshot -m region"))
hl.bind("XF86MonBrightnessUp",     gated(globalCmd("brightnessUp"), "brightnessctl -e4 -n2 set 5%+"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",   gated(globalCmd("brightnessDown"), "brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext",           gated(globalCmd("mediaNext"), "playerctl next"),         { locked = true })
hl.bind("XF86AudioPause",          gated(globalCmd("mediaToggle"), "playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",           gated(globalCmd("mediaToggle"), "playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",           gated(globalCmd("mediaPrev"), "playerctl previous"),     { locked = true })

-- Global shortcuts: inert unless caelestia has registered them
hl.bind(mainMod .. " + SUPER_L",           hl.dsp.global("caelestia:launcher"), { release = true })
hl.bind(mainMod .. " + K",                 hl.dsp.global("caelestia:showall"))
hl.bind(mainMod .. " + N",                 hl.dsp.global("caelestia:sidebar"))
hl.bind("CTRL + ALT + Delete",             hl.dsp.global("caelestia:session"))
hl.bind("CTRL + ALT + C",                  hl.dsp.global("caelestia:clearNotifs"), { locked = true })
hl.bind(mainMod .. " + SHIFT + ALT + S",   hl.dsp.global("caelestia:screenshot"))
hl.bind("CTRL + " .. mainMod .. " + Space",     hl.dsp.global("caelestia:mediaToggle"), { locked = true })
hl.bind("CTRL + " .. mainMod .. " + Equal",     hl.dsp.global("caelestia:mediaNext"),   { locked = true })
hl.bind("CTRL + " .. mainMod .. " + Minus",     hl.dsp.global("caelestia:mediaPrev"),   { locked = true })
hl.bind("CTRL + " .. mainMod .. " + Backspace", hl.dsp.global("caelestia:mediaStop"),   { locked = true })
hl.bind("XF86AudioStop",                   hl.dsp.global("caelestia:mediaStop"),   { locked = true })
hl.bind(mainMod .. " + ALT + M",           hl.dsp.global("caelestia:spotify"))
hl.bind(mainMod .. " + ALT + T",           hl.dsp.global("caelestia:clock"))

-- CLI-driven actions: no fallback, so a no-op under other configs
hl.bind("Print",                         gated("caelestia screenshot"))
hl.bind(mainMod .. " + Period",          gated("caelestia emoji -p"))
hl.bind(mainMod .. " + ALT + V",         gated("caelestia clipboard -d"))
hl.bind("CTRL + ALT + R",                gated("caelestia record"))
hl.bind(mainMod .. " + ALT + R",         gated("caelestia record -s"))
hl.bind(mainMod .. " + SHIFT + ALT + R", gated("caelestia record -r"))
hl.bind(mainMod .. " + ALT + L",         gated("caelestia shell -d; " .. globalCmd("lock")))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful
--
--


local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    -- x clears the 56px left bar (CaelestiaReplicate) by the same 20px the
    -- window keeps from every other edge; harmless under the top-bar config.
    move  = "76 monitor_h-120",
    float = true,
})

-- Caelestia Spotify window (modules/spotify in the shell config)
hl.window_rule({
    name   = "caelestia-spotify-window",
    match  = { class = "^org\\.quickshell$", title = "^Spotify$" },

    float  = true,
    size   = "520 720",
    center = true,
})

-- Caelestia clock window (modules/clock in the shell config)
hl.window_rule({
    name   = "caelestia-clock-window",
    match  = { class = "^org\\.quickshell$", title = "^Clock$" },

    float  = true,
    size   = "360 200",
    center = true,
})
