-- AUTOGENERATED from ~/.config/theme/templates/hypr-colors.lua
-- Regenerated on every wallpaper change. Do not edit -- edit the template.
--
-- Consumed by hyprland.lua via `require("colors")`. Returning a table (rather
-- than calling hl.config directly) keeps hyprland.lua the single place where
-- layout and behaviour live; this file only supplies colour values.

return {
    -- Focused window border: a gradient from primary to tertiary.
    active_border = {
        colors = {
            "rgba({{colors.primary.default.hex_stripped}}ee)",
            "rgba({{colors.tertiary.default.hex_stripped}}ee)",
        },
        angle = 45,
    },

    -- Unfocused window border: muted, low contrast, stays out of the way.
    inactive_border = "rgba({{colors.outline_variant.default.hex_stripped}}aa)",

    -- Drop shadow, tinted to the wallpaper instead of neutral black.
    shadow_color = 0xee{{colors.shadow.default.hex_stripped}},

    -- Plain hex values, for anything else in hyprland.lua that wants one.
    primary   = "{{colors.primary.default.hex}}",
    surface   = "{{colors.surface.default.hex}}",
    on_surface = "{{colors.on_surface.default.hex}}",
}
